// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.13.0
// source: resultcode.proto

package resultcode

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type RESULT_CODE int32

const (
	// 0-100 保留
	RESULT_CODE_RET_OK          RESULT_CODE = 0
	RESULT_CODE_RET_SYS_ERR     RESULT_CODE = 1
	RESULT_CODE_RET_MYSQL_ERR   RESULT_CODE = 2
	RESULT_CODE_RET_REDIS_ERR   RESULT_CODE = 3
	RESULT_CODE_RET_NETWORK_ERR RESULT_CODE = 4
	RESULT_CODE_RET_UNKNOWN_ERR RESULT_CODE = 5
	// 101...
	RESULT_CODE_RET_INVALID_ARGS RESULT_CODE = 101
)

// Enum value maps for RESULT_CODE.
var (
	RESULT_CODE_name = map[int32]string{
		0:   "RET_OK",
		1:   "RET_SYS_ERR",
		2:   "RET_MYSQL_ERR",
		3:   "RET_REDIS_ERR",
		4:   "RET_NETWORK_ERR",
		5:   "RET_UNKNOWN_ERR",
		101: "RET_INVALID_ARGS",
	}
	RESULT_CODE_value = map[string]int32{
		"RET_OK":           0,
		"RET_SYS_ERR":      1,
		"RET_MYSQL_ERR":    2,
		"RET_REDIS_ERR":    3,
		"RET_NETWORK_ERR":  4,
		"RET_UNKNOWN_ERR":  5,
		"RET_INVALID_ARGS": 101,
	}
)

func (x RESULT_CODE) Enum() *RESULT_CODE {
	p := new(RESULT_CODE)
	*p = x
	return p
}

func (x RESULT_CODE) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RESULT_CODE) Descriptor() protoreflect.EnumDescriptor {
	return file_resultcode_proto_enumTypes[0].Descriptor()
}

func (RESULT_CODE) Type() protoreflect.EnumType {
	return &file_resultcode_proto_enumTypes[0]
}

func (x RESULT_CODE) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RESULT_CODE.Descriptor instead.
func (RESULT_CODE) EnumDescriptor() ([]byte, []int) {
	return file_resultcode_proto_rawDescGZIP(), []int{0}
}

var File_resultcode_proto protoreflect.FileDescriptor

var file_resultcode_proto_rawDesc = []byte{
	0x0a, 0x10, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x63, 0x6f, 0x64, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x0a, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x63, 0x6f, 0x64, 0x65, 0x2a, 0x90,
	0x01, 0x0a, 0x0b, 0x52, 0x45, 0x53, 0x55, 0x4c, 0x54, 0x5f, 0x43, 0x4f, 0x44, 0x45, 0x12, 0x0a,
	0x0a, 0x06, 0x52, 0x45, 0x54, 0x5f, 0x4f, 0x4b, 0x10, 0x00, 0x12, 0x0f, 0x0a, 0x0b, 0x52, 0x45,
	0x54, 0x5f, 0x53, 0x59, 0x53, 0x5f, 0x45, 0x52, 0x52, 0x10, 0x01, 0x12, 0x11, 0x0a, 0x0d, 0x52,
	0x45, 0x54, 0x5f, 0x4d, 0x59, 0x53, 0x51, 0x4c, 0x5f, 0x45, 0x52, 0x52, 0x10, 0x02, 0x12, 0x11,
	0x0a, 0x0d, 0x52, 0x45, 0x54, 0x5f, 0x52, 0x45, 0x44, 0x49, 0x53, 0x5f, 0x45, 0x52, 0x52, 0x10,
	0x03, 0x12, 0x13, 0x0a, 0x0f, 0x52, 0x45, 0x54, 0x5f, 0x4e, 0x45, 0x54, 0x57, 0x4f, 0x52, 0x4b,
	0x5f, 0x45, 0x52, 0x52, 0x10, 0x04, 0x12, 0x13, 0x0a, 0x0f, 0x52, 0x45, 0x54, 0x5f, 0x55, 0x4e,
	0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x5f, 0x45, 0x52, 0x52, 0x10, 0x05, 0x12, 0x14, 0x0a, 0x10, 0x52,
	0x45, 0x54, 0x5f, 0x49, 0x4e, 0x56, 0x41, 0x4c, 0x49, 0x44, 0x5f, 0x41, 0x52, 0x47, 0x53, 0x10,
	0x65, 0x42, 0x2c, 0x5a, 0x2a, 0x6e, 0x65, 0x77, 0x5f, 0x61, 0x64, 0x64, 0x73, 0x76, 0x63, 0x2f,
	0x70, 0x62, 0x2f, 0x67, 0x65, 0x6e, 0x2d, 0x67, 0x6f, 0x2f, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x63, 0x6f, 0x64, 0x65, 0x3b, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x63, 0x6f, 0x64, 0x65, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_resultcode_proto_rawDescOnce sync.Once
	file_resultcode_proto_rawDescData = file_resultcode_proto_rawDesc
)

func file_resultcode_proto_rawDescGZIP() []byte {
	file_resultcode_proto_rawDescOnce.Do(func() {
		file_resultcode_proto_rawDescData = protoimpl.X.CompressGZIP(file_resultcode_proto_rawDescData)
	})
	return file_resultcode_proto_rawDescData
}

var file_resultcode_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_resultcode_proto_goTypes = []interface{}{
	(RESULT_CODE)(0), // 0: resultcode.RESULT_CODE
}
var file_resultcode_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_resultcode_proto_init() }
func file_resultcode_proto_init() {
	if File_resultcode_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_resultcode_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_resultcode_proto_goTypes,
		DependencyIndexes: file_resultcode_proto_depIdxs,
		EnumInfos:         file_resultcode_proto_enumTypes,
	}.Build()
	File_resultcode_proto = out.File
	file_resultcode_proto_rawDesc = nil
	file_resultcode_proto_goTypes = nil
	file_resultcode_proto_depIdxs = nil
}
