// Code generated by protoc-gen-go. DO NOT EDIT.
// source: common/common.proto

package pbcommon

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Plat int32

const (
	Plat_pc      Plat = 0
	Plat_ios     Plat = 1
	Plat_android Plat = 2
)

var Plat_name = map[int32]string{
	0: "pc",
	1: "ios",
	2: "android",
}

var Plat_value = map[string]int32{
	"pc":      0,
	"ios":     1,
	"android": 2,
}

func (x Plat) String() string {
	return proto.EnumName(Plat_name, int32(x))
}

func (Plat) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_8f954d82c0b891f6, []int{0}
}

type BaseReq struct {
	Plat                 Plat     `protobuf:"varint,1,opt,name=plat,proto3,enum=pbcommon.Plat" json:"plat,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BaseReq) Reset()         { *m = BaseReq{} }
func (m *BaseReq) String() string { return proto.CompactTextString(m) }
func (*BaseReq) ProtoMessage()    {}
func (*BaseReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f954d82c0b891f6, []int{0}
}

func (m *BaseReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BaseReq.Unmarshal(m, b)
}
func (m *BaseReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BaseReq.Marshal(b, m, deterministic)
}
func (m *BaseReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BaseReq.Merge(m, src)
}
func (m *BaseReq) XXX_Size() int {
	return xxx_messageInfo_BaseReq.Size(m)
}
func (m *BaseReq) XXX_DiscardUnknown() {
	xxx_messageInfo_BaseReq.DiscardUnknown(m)
}

var xxx_messageInfo_BaseReq proto.InternalMessageInfo

func (m *BaseReq) GetPlat() Plat {
	if m != nil {
		return m.Plat
	}
	return Plat_pc
}

type BaseRsp struct {
	ErrCode              R        `protobuf:"varint,1,opt,name=err_code,json=errCode,proto3,enum=pbcommon.R" json:"err_code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BaseRsp) Reset()         { *m = BaseRsp{} }
func (m *BaseRsp) String() string { return proto.CompactTextString(m) }
func (*BaseRsp) ProtoMessage()    {}
func (*BaseRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f954d82c0b891f6, []int{1}
}

func (m *BaseRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BaseRsp.Unmarshal(m, b)
}
func (m *BaseRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BaseRsp.Marshal(b, m, deterministic)
}
func (m *BaseRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BaseRsp.Merge(m, src)
}
func (m *BaseRsp) XXX_Size() int {
	return xxx_messageInfo_BaseRsp.Size(m)
}
func (m *BaseRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_BaseRsp.DiscardUnknown(m)
}

var xxx_messageInfo_BaseRsp proto.InternalMessageInfo

func (m *BaseRsp) GetErrCode() R {
	if m != nil {
		return m.ErrCode
	}
	return R_OK
}

func init() {
	proto.RegisterEnum("pbcommon.Plat", Plat_name, Plat_value)
	proto.RegisterType((*BaseReq)(nil), "pbcommon.BaseReq")
	proto.RegisterType((*BaseRsp)(nil), "pbcommon.BaseRsp")
}

func init() {
	proto.RegisterFile("common/common.proto", fileDescriptor_8f954d82c0b891f6)
}

var fileDescriptor_8f954d82c0b891f6 = []byte{
	// 197 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x44, 0x8e, 0x51, 0x4b, 0x86, 0x30,
	0x14, 0x86, 0xd3, 0xc4, 0xc9, 0x11, 0x44, 0xd6, 0x45, 0xd1, 0x55, 0x59, 0x44, 0x04, 0x2a, 0xd5,
	0x65, 0x77, 0xf6, 0x07, 0x62, 0x97, 0xdd, 0xc4, 0x74, 0x07, 0x13, 0xa6, 0x67, 0x6d, 0xeb, 0xff,
	0x7f, 0xe8, 0x94, 0xef, 0x6a, 0xef, 0x78, 0xdf, 0xe7, 0xe1, 0xc0, 0xd5, 0x40, 0xf3, 0x4c, 0x4b,
	0x1b, 0x9e, 0xc6, 0x58, 0xf2, 0xc4, 0x33, 0xd3, 0x87, 0xff, 0xed, 0xf5, 0x5e, 0x5b, 0x74, 0xff,
	0xda, 0x0f, 0xa4, 0x30, 0x4c, 0xaa, 0x1a, 0x58, 0x27, 0x1d, 0x0a, 0xfc, 0xe3, 0x15, 0x24, 0x46,
	0x4b, 0x7f, 0x13, 0xdd, 0x45, 0xcf, 0xc5, 0x5b, 0xd1, 0x1c, 0x70, 0xf3, 0xa5, 0xa5, 0x17, 0x5b,
	0x57, 0xbd, 0xee, 0x73, 0x67, 0xf8, 0x13, 0x64, 0x68, 0xed, 0xcf, 0xea, 0xda, 0x91, 0xfc, 0x8c,
	0x08, 0xc1, 0xd0, 0xda, 0x4f, 0x52, 0xf8, 0xf2, 0x08, 0xc9, 0x2a, 0xe0, 0x29, 0xc4, 0x66, 0x28,
	0x2f, 0x38, 0x83, 0xcb, 0x89, 0x5c, 0x19, 0xf1, 0x1c, 0x98, 0x5c, 0x94, 0xa5, 0x49, 0x95, 0x71,
	0xf7, 0xf0, 0x7d, 0xff, 0x8b, 0x5a, 0x53, 0x6b, 0xfa, 0x76, 0xc4, 0xa5, 0x1e, 0xd7, 0x14, 0x64,
	0x1f, 0x47, 0xe8, 0xd3, 0xed, 0xe6, 0xf7, 0x53, 0x00, 0x00, 0x00, 0xff, 0xff, 0xbd, 0x6b, 0xe7,
	0x02, 0xed, 0x00, 0x00, 0x00,
}
