// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.5.0
// source: common/resultcode.proto

package pbcommon

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type R int32

const (
	// 0-100 保留
	R_OK          R = 0
	R_SYS_ERR     R = 1
	R_MYSQL_ERR   R = 2
	R_REDIS_ERR   R = 3
	R_NETWORK_ERR R = 4
	R_UNKNOWN_ERR R = 5
	R_RPC_ERR     R = 6
	// 101...
	R_INVALID_ARGS R = 101
)

// Enum value maps for R.
var (
	R_name = map[int32]string{
		0:   "OK",
		1:   "SYS_ERR",
		2:   "MYSQL_ERR",
		3:   "REDIS_ERR",
		4:   "NETWORK_ERR",
		5:   "UNKNOWN_ERR",
		6:   "RPC_ERR",
		101: "INVALID_ARGS",
	}
	R_value = map[string]int32{
		"OK":           0,
		"SYS_ERR":      1,
		"MYSQL_ERR":    2,
		"REDIS_ERR":    3,
		"NETWORK_ERR":  4,
		"UNKNOWN_ERR":  5,
		"RPC_ERR":      6,
		"INVALID_ARGS": 101,
	}
)

func (x R) Enum() *R {
	p := new(R)
	*p = x
	return p
}

func (x R) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (R) Descriptor() protoreflect.EnumDescriptor {
	return file_common_resultcode_proto_enumTypes[0].Descriptor()
}

func (R) Type() protoreflect.EnumType {
	return &file_common_resultcode_proto_enumTypes[0]
}

func (x R) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use R.Descriptor instead.
func (R) EnumDescriptor() ([]byte, []int) {
	return file_common_resultcode_proto_rawDescGZIP(), []int{0}
}

var File_common_resultcode_proto protoreflect.FileDescriptor

var file_common_resultcode_proto_rawDesc = []byte{
	0x0a, 0x17, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x63,
	0x6f, 0x64, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x70, 0x62, 0x63, 0x6f, 0x6d,
	0x6d, 0x6f, 0x6e, 0x2a, 0x77, 0x0a, 0x01, 0x52, 0x12, 0x06, 0x0a, 0x02, 0x4f, 0x4b, 0x10, 0x00,
	0x12, 0x0b, 0x0a, 0x07, 0x53, 0x59, 0x53, 0x5f, 0x45, 0x52, 0x52, 0x10, 0x01, 0x12, 0x0d, 0x0a,
	0x09, 0x4d, 0x59, 0x53, 0x51, 0x4c, 0x5f, 0x45, 0x52, 0x52, 0x10, 0x02, 0x12, 0x0d, 0x0a, 0x09,
	0x52, 0x45, 0x44, 0x49, 0x53, 0x5f, 0x45, 0x52, 0x52, 0x10, 0x03, 0x12, 0x0f, 0x0a, 0x0b, 0x4e,
	0x45, 0x54, 0x57, 0x4f, 0x52, 0x4b, 0x5f, 0x45, 0x52, 0x52, 0x10, 0x04, 0x12, 0x0f, 0x0a, 0x0b,
	0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x5f, 0x45, 0x52, 0x52, 0x10, 0x05, 0x12, 0x0b, 0x0a,
	0x07, 0x52, 0x50, 0x43, 0x5f, 0x45, 0x52, 0x52, 0x10, 0x06, 0x12, 0x10, 0x0a, 0x0c, 0x49, 0x4e,
	0x56, 0x41, 0x4c, 0x49, 0x44, 0x5f, 0x41, 0x52, 0x47, 0x53, 0x10, 0x65, 0x42, 0x23, 0x5a, 0x21,
	0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x2f, 0x70, 0x62, 0x2f, 0x67, 0x65, 0x6e, 0x2d, 0x67, 0x6f, 0x2f,
	0x70, 0x62, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x3b, 0x70, 0x62, 0x63, 0x6f, 0x6d, 0x6d, 0x6f,
	0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_common_resultcode_proto_rawDescOnce sync.Once
	file_common_resultcode_proto_rawDescData = file_common_resultcode_proto_rawDesc
)

func file_common_resultcode_proto_rawDescGZIP() []byte {
	file_common_resultcode_proto_rawDescOnce.Do(func() {
		file_common_resultcode_proto_rawDescData = protoimpl.X.CompressGZIP(file_common_resultcode_proto_rawDescData)
	})
	return file_common_resultcode_proto_rawDescData
}

var file_common_resultcode_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_common_resultcode_proto_goTypes = []interface{}{
	(R)(0), // 0: pbcommon.R
}
var file_common_resultcode_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_common_resultcode_proto_init() }
func file_common_resultcode_proto_init() {
	if File_common_resultcode_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_common_resultcode_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_resultcode_proto_goTypes,
		DependencyIndexes: file_common_resultcode_proto_depIdxs,
		EnumInfos:         file_common_resultcode_proto_enumTypes,
	}.Build()
	File_common_resultcode_proto = out.File
	file_common_resultcode_proto_rawDesc = nil
	file_common_resultcode_proto_goTypes = nil
	file_common_resultcode_proto_depIdxs = nil
}
