// Code generated by protoc-gen-go. DO NOT EDIT.
// source: hello.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	pbcommon "hello/pb/gen-go/pbcommon"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SayHiRequest struct {
	BaseReq              *pbcommon.BaseReq `protobuf:"bytes,1,opt,name=base_req,json=baseReq,proto3" json:"base_req,omitempty"`
	Name                 string            `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *SayHiRequest) Reset()         { *m = SayHiRequest{} }
func (m *SayHiRequest) String() string { return proto.CompactTextString(m) }
func (*SayHiRequest) ProtoMessage()    {}
func (*SayHiRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_61ef911816e0a8ce, []int{0}
}

func (m *SayHiRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SayHiRequest.Unmarshal(m, b)
}
func (m *SayHiRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SayHiRequest.Marshal(b, m, deterministic)
}
func (m *SayHiRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SayHiRequest.Merge(m, src)
}
func (m *SayHiRequest) XXX_Size() int {
	return xxx_messageInfo_SayHiRequest.Size(m)
}
func (m *SayHiRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SayHiRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SayHiRequest proto.InternalMessageInfo

func (m *SayHiRequest) GetBaseReq() *pbcommon.BaseReq {
	if m != nil {
		return m.BaseReq
	}
	return nil
}

func (m *SayHiRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type SayHiReply struct {
	BaseRsp              *pbcommon.BaseRsp `protobuf:"bytes,2,opt,name=base_rsp,json=baseRsp,proto3" json:"base_rsp,omitempty"`
	Reply                string            `protobuf:"bytes,1,opt,name=reply,proto3" json:"reply,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *SayHiReply) Reset()         { *m = SayHiReply{} }
func (m *SayHiReply) String() string { return proto.CompactTextString(m) }
func (*SayHiReply) ProtoMessage()    {}
func (*SayHiReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_61ef911816e0a8ce, []int{1}
}

func (m *SayHiReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SayHiReply.Unmarshal(m, b)
}
func (m *SayHiReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SayHiReply.Marshal(b, m, deterministic)
}
func (m *SayHiReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SayHiReply.Merge(m, src)
}
func (m *SayHiReply) XXX_Size() int {
	return xxx_messageInfo_SayHiReply.Size(m)
}
func (m *SayHiReply) XXX_DiscardUnknown() {
	xxx_messageInfo_SayHiReply.DiscardUnknown(m)
}

var xxx_messageInfo_SayHiReply proto.InternalMessageInfo

func (m *SayHiReply) GetBaseRsp() *pbcommon.BaseRsp {
	if m != nil {
		return m.BaseRsp
	}
	return nil
}

func (m *SayHiReply) GetReply() string {
	if m != nil {
		return m.Reply
	}
	return ""
}

func init() {
	proto.RegisterType((*SayHiRequest)(nil), "pb.SayHiRequest")
	proto.RegisterType((*SayHiReply)(nil), "pb.SayHiReply")
}

func init() {
	proto.RegisterFile("hello.proto", fileDescriptor_61ef911816e0a8ce)
}

var fileDescriptor_61ef911816e0a8ce = []byte{
	// 214 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xce, 0x48, 0xcd, 0xc9,
	0xc9, 0xd7, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2a, 0x48, 0x92, 0x12, 0x4e, 0xce, 0xcf,
	0xcd, 0xcd, 0xcf, 0xd3, 0x87, 0x50, 0x10, 0x09, 0xa5, 0x00, 0x2e, 0x9e, 0xe0, 0xc4, 0x4a, 0x8f,
	0xcc, 0xa0, 0xd4, 0xc2, 0xd2, 0xd4, 0xe2, 0x12, 0x21, 0x1d, 0x2e, 0x8e, 0xa4, 0xc4, 0xe2, 0xd4,
	0xf8, 0xa2, 0xd4, 0x42, 0x09, 0x46, 0x05, 0x46, 0x0d, 0x6e, 0x23, 0x41, 0xbd, 0x82, 0x24, 0xa8,
	0x16, 0xa7, 0xc4, 0xe2, 0xd4, 0xa0, 0xd4, 0xc2, 0x20, 0xf6, 0x24, 0x08, 0x43, 0x48, 0x88, 0x8b,
	0x25, 0x2f, 0x31, 0x37, 0x55, 0x82, 0x49, 0x81, 0x51, 0x83, 0x33, 0x08, 0xcc, 0x56, 0x0a, 0xe0,
	0xe2, 0x82, 0x9a, 0x58, 0x90, 0x53, 0x89, 0x30, 0xaf, 0xb8, 0x00, 0xac, 0x0a, 0xd3, 0xbc, 0xe2,
	0x02, 0xa8, 0x79, 0xc5, 0x05, 0x42, 0x22, 0x5c, 0xac, 0x45, 0x20, 0x6d, 0x60, 0xab, 0x39, 0x83,
	0x20, 0x1c, 0x23, 0x23, 0x2e, 0x56, 0x0f, 0x90, 0x5f, 0x84, 0x34, 0xb9, 0x58, 0xc1, 0x46, 0x0b,
	0x09, 0xe8, 0x15, 0x24, 0xe9, 0x21, 0xbb, 0x5b, 0x8a, 0x0f, 0x49, 0xa4, 0x20, 0xa7, 0xd2, 0x49,
	0x3c, 0x4a, 0x14, 0xec, 0x7f, 0xfd, 0x82, 0x24, 0xfd, 0xf4, 0xd4, 0x3c, 0xdd, 0x74, 0x10, 0xcb,
	0xba, 0x20, 0x29, 0x89, 0x0d, 0xec, 0x6f, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0x54, 0x36,
	0x43, 0x73, 0x1f, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// HelloClient is the client API for Hello service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type HelloClient interface {
	SayHi(ctx context.Context, in *SayHiRequest, opts ...grpc.CallOption) (*SayHiReply, error)
}

type helloClient struct {
	cc grpc.ClientConnInterface
}

func NewHelloClient(cc grpc.ClientConnInterface) HelloClient {
	return &helloClient{cc}
}

func (c *helloClient) SayHi(ctx context.Context, in *SayHiRequest, opts ...grpc.CallOption) (*SayHiReply, error) {
	out := new(SayHiReply)
	err := c.cc.Invoke(ctx, "/pb.Hello/SayHi", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HelloServer is the server API for Hello service.
type HelloServer interface {
	SayHi(context.Context, *SayHiRequest) (*SayHiReply, error)
}

// UnimplementedHelloServer can be embedded to have forward compatible implementations.
type UnimplementedHelloServer struct {
}

func (*UnimplementedHelloServer) SayHi(ctx context.Context, req *SayHiRequest) (*SayHiReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayHi not implemented")
}

func RegisterHelloServer(s *grpc.Server, srv HelloServer) {
	s.RegisterService(&_Hello_serviceDesc, srv)
}

func _Hello_SayHi_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SayHiRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HelloServer).SayHi(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Hello/SayHi",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HelloServer).SayHi(ctx, req.(*SayHiRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Hello_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Hello",
	HandlerType: (*HelloServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHi",
			Handler:    _Hello_SayHi_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "hello.proto",
}
