// Code generated by protoc-gen-go. DO NOT EDIT.
// source: hello.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	pbcommon "hello/pb/gen-go/pbcommon"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SayHiRequest struct {
	BaseReq              *pbcommon.BaseReq `protobuf:"bytes,1,opt,name=base_req,json=baseReq,proto3" json:"base_req,omitempty"`
	Name                 string            `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *SayHiRequest) Reset()         { *m = SayHiRequest{} }
func (m *SayHiRequest) String() string { return proto.CompactTextString(m) }
func (*SayHiRequest) ProtoMessage()    {}
func (*SayHiRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_61ef911816e0a8ce, []int{0}
}

func (m *SayHiRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SayHiRequest.Unmarshal(m, b)
}
func (m *SayHiRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SayHiRequest.Marshal(b, m, deterministic)
}
func (m *SayHiRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SayHiRequest.Merge(m, src)
}
func (m *SayHiRequest) XXX_Size() int {
	return xxx_messageInfo_SayHiRequest.Size(m)
}
func (m *SayHiRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SayHiRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SayHiRequest proto.InternalMessageInfo

func (m *SayHiRequest) GetBaseReq() *pbcommon.BaseReq {
	if m != nil {
		return m.BaseReq
	}
	return nil
}

func (m *SayHiRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type SayHiResponse struct {
	BaseRsp              *pbcommon.BaseRsp `protobuf:"bytes,2,opt,name=base_rsp,json=baseRsp,proto3" json:"base_rsp,omitempty"`
	Reply                string            `protobuf:"bytes,1,opt,name=reply,proto3" json:"reply,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *SayHiResponse) Reset()         { *m = SayHiResponse{} }
func (m *SayHiResponse) String() string { return proto.CompactTextString(m) }
func (*SayHiResponse) ProtoMessage()    {}
func (*SayHiResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_61ef911816e0a8ce, []int{1}
}

func (m *SayHiResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SayHiResponse.Unmarshal(m, b)
}
func (m *SayHiResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SayHiResponse.Marshal(b, m, deterministic)
}
func (m *SayHiResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SayHiResponse.Merge(m, src)
}
func (m *SayHiResponse) XXX_Size() int {
	return xxx_messageInfo_SayHiResponse.Size(m)
}
func (m *SayHiResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SayHiResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SayHiResponse proto.InternalMessageInfo

func (m *SayHiResponse) GetBaseRsp() *pbcommon.BaseRsp {
	if m != nil {
		return m.BaseRsp
	}
	return nil
}

func (m *SayHiResponse) GetReply() string {
	if m != nil {
		return m.Reply
	}
	return ""
}

type MakeADateRequest struct {
	BaseReq              *pbcommon.BaseReq `protobuf:"bytes,1,opt,name=base_req,json=baseReq,proto3" json:"base_req,omitempty"`
	DateStr              string            `protobuf:"bytes,2,opt,name=date_str,json=dateStr,proto3" json:"date_str,omitempty"`
	WantSay              string            `protobuf:"bytes,3,opt,name=want_say,json=wantSay,proto3" json:"want_say,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *MakeADateRequest) Reset()         { *m = MakeADateRequest{} }
func (m *MakeADateRequest) String() string { return proto.CompactTextString(m) }
func (*MakeADateRequest) ProtoMessage()    {}
func (*MakeADateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_61ef911816e0a8ce, []int{2}
}

func (m *MakeADateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MakeADateRequest.Unmarshal(m, b)
}
func (m *MakeADateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MakeADateRequest.Marshal(b, m, deterministic)
}
func (m *MakeADateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MakeADateRequest.Merge(m, src)
}
func (m *MakeADateRequest) XXX_Size() int {
	return xxx_messageInfo_MakeADateRequest.Size(m)
}
func (m *MakeADateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MakeADateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MakeADateRequest proto.InternalMessageInfo

func (m *MakeADateRequest) GetBaseReq() *pbcommon.BaseReq {
	if m != nil {
		return m.BaseReq
	}
	return nil
}

func (m *MakeADateRequest) GetDateStr() string {
	if m != nil {
		return m.DateStr
	}
	return ""
}

func (m *MakeADateRequest) GetWantSay() string {
	if m != nil {
		return m.WantSay
	}
	return ""
}

type MakeADateResponse struct {
	BaseRsp              *pbcommon.BaseRsp `protobuf:"bytes,2,opt,name=base_rsp,json=baseRsp,proto3" json:"base_rsp,omitempty"`
	Reply                string            `protobuf:"bytes,1,opt,name=reply,proto3" json:"reply,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *MakeADateResponse) Reset()         { *m = MakeADateResponse{} }
func (m *MakeADateResponse) String() string { return proto.CompactTextString(m) }
func (*MakeADateResponse) ProtoMessage()    {}
func (*MakeADateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_61ef911816e0a8ce, []int{3}
}

func (m *MakeADateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MakeADateResponse.Unmarshal(m, b)
}
func (m *MakeADateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MakeADateResponse.Marshal(b, m, deterministic)
}
func (m *MakeADateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MakeADateResponse.Merge(m, src)
}
func (m *MakeADateResponse) XXX_Size() int {
	return xxx_messageInfo_MakeADateResponse.Size(m)
}
func (m *MakeADateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MakeADateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MakeADateResponse proto.InternalMessageInfo

func (m *MakeADateResponse) GetBaseRsp() *pbcommon.BaseRsp {
	if m != nil {
		return m.BaseRsp
	}
	return nil
}

func (m *MakeADateResponse) GetReply() string {
	if m != nil {
		return m.Reply
	}
	return ""
}

type UpdateUserInfoRequest struct {
	BaseReq              *pbcommon.BaseReq `protobuf:"bytes,1,opt,name=base_req,json=baseReq,proto3" json:"base_req,omitempty"`
	UserId               uint32            `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	NewName              string            `protobuf:"bytes,3,opt,name=new_name,json=newName,proto3" json:"new_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *UpdateUserInfoRequest) Reset()         { *m = UpdateUserInfoRequest{} }
func (m *UpdateUserInfoRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateUserInfoRequest) ProtoMessage()    {}
func (*UpdateUserInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_61ef911816e0a8ce, []int{4}
}

func (m *UpdateUserInfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateUserInfoRequest.Unmarshal(m, b)
}
func (m *UpdateUserInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateUserInfoRequest.Marshal(b, m, deterministic)
}
func (m *UpdateUserInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateUserInfoRequest.Merge(m, src)
}
func (m *UpdateUserInfoRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateUserInfoRequest.Size(m)
}
func (m *UpdateUserInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateUserInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateUserInfoRequest proto.InternalMessageInfo

func (m *UpdateUserInfoRequest) GetBaseReq() *pbcommon.BaseReq {
	if m != nil {
		return m.BaseReq
	}
	return nil
}

func (m *UpdateUserInfoRequest) GetUserId() uint32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *UpdateUserInfoRequest) GetNewName() string {
	if m != nil {
		return m.NewName
	}
	return ""
}

type UpdateUserInfoResponse struct {
	BaseRsp              *pbcommon.BaseRsp `protobuf:"bytes,1,opt,name=base_rsp,json=baseRsp,proto3" json:"base_rsp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *UpdateUserInfoResponse) Reset()         { *m = UpdateUserInfoResponse{} }
func (m *UpdateUserInfoResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateUserInfoResponse) ProtoMessage()    {}
func (*UpdateUserInfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_61ef911816e0a8ce, []int{5}
}

func (m *UpdateUserInfoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateUserInfoResponse.Unmarshal(m, b)
}
func (m *UpdateUserInfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateUserInfoResponse.Marshal(b, m, deterministic)
}
func (m *UpdateUserInfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateUserInfoResponse.Merge(m, src)
}
func (m *UpdateUserInfoResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateUserInfoResponse.Size(m)
}
func (m *UpdateUserInfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateUserInfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateUserInfoResponse proto.InternalMessageInfo

func (m *UpdateUserInfoResponse) GetBaseRsp() *pbcommon.BaseRsp {
	if m != nil {
		return m.BaseRsp
	}
	return nil
}

func init() {
	proto.RegisterType((*SayHiRequest)(nil), "pb.SayHiRequest")
	proto.RegisterType((*SayHiResponse)(nil), "pb.SayHiResponse")
	proto.RegisterType((*MakeADateRequest)(nil), "pb.MakeADateRequest")
	proto.RegisterType((*MakeADateResponse)(nil), "pb.MakeADateResponse")
	proto.RegisterType((*UpdateUserInfoRequest)(nil), "pb.UpdateUserInfoRequest")
	proto.RegisterType((*UpdateUserInfoResponse)(nil), "pb.UpdateUserInfoResponse")
}

func init() {
	proto.RegisterFile("hello.proto", fileDescriptor_61ef911816e0a8ce)
}

var fileDescriptor_61ef911816e0a8ce = []byte{
	// 368 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x53, 0x4d, 0x4f, 0x02, 0x31,
	0x10, 0xcd, 0xa2, 0x7c, 0x0d, 0x62, 0xa0, 0x82, 0xc0, 0x9e, 0xc8, 0x9e, 0x38, 0xe0, 0x92, 0xe0,
	0xc5, 0xc4, 0x93, 0xc4, 0x28, 0x1c, 0x34, 0x66, 0x37, 0xc4, 0xc4, 0xcb, 0xa6, 0x95, 0x11, 0x89,
	0xd0, 0x2d, 0xdb, 0x45, 0xb2, 0xff, 0xcc, 0x9f, 0x67, 0xda, 0x6d, 0x14, 0x91, 0xc4, 0x84, 0x78,
	0xea, 0x4c, 0x5f, 0xfb, 0xe6, 0xbd, 0x4e, 0x07, 0x4a, 0xaf, 0x38, 0x9f, 0x87, 0xae, 0x88, 0xc2,
	0x38, 0x24, 0x19, 0xc1, 0xec, 0x93, 0xe7, 0x70, 0xb1, 0x08, 0x79, 0x2f, 0x5d, 0x52, 0xc0, 0x79,
	0x80, 0x23, 0x9f, 0x26, 0xc3, 0x99, 0x87, 0xcb, 0x15, 0xca, 0x98, 0x74, 0xa1, 0xc0, 0xa8, 0xc4,
	0x20, 0xc2, 0x65, 0xd3, 0x6a, 0x5b, 0x9d, 0x52, 0xbf, 0xea, 0x0a, 0x66, 0xae, 0x0c, 0xa8, 0x44,
	0x0f, 0x97, 0x5e, 0x9e, 0xa5, 0x01, 0x21, 0x70, 0xc8, 0xe9, 0x02, 0x9b, 0x99, 0xb6, 0xd5, 0x29,
	0x7a, 0x3a, 0x76, 0x7c, 0x28, 0x1b, 0x46, 0x29, 0x42, 0x2e, 0xf1, 0x9b, 0x52, 0x0a, 0x7d, 0xf0,
	0x37, 0xa5, 0x14, 0x86, 0x52, 0x0a, 0x52, 0x83, 0x6c, 0x84, 0x62, 0x9e, 0xe8, 0xea, 0x45, 0x2f,
	0x4d, 0x9c, 0x77, 0xa8, 0xdc, 0xd1, 0x37, 0xbc, 0xba, 0xa6, 0x31, 0xee, 0x27, 0xb5, 0x05, 0x85,
	0x09, 0x8d, 0x31, 0x90, 0x71, 0x64, 0xe4, 0xe6, 0x55, 0xee, 0xc7, 0x91, 0x82, 0xd6, 0x94, 0xc7,
	0x81, 0xa4, 0x49, 0xf3, 0x20, 0x85, 0x54, 0xee, 0xd3, 0xc4, 0x79, 0x84, 0xea, 0x46, 0xdd, 0x7f,
	0x34, 0x94, 0x40, 0x7d, 0x2c, 0x94, 0x80, 0xb1, 0xc4, 0x68, 0xc4, 0x5f, 0xc2, 0xfd, 0x5c, 0x35,
	0x20, 0xbf, 0x92, 0x18, 0x05, 0xb3, 0x89, 0x56, 0x52, 0xf6, 0x72, 0x2a, 0x1d, 0x4d, 0x94, 0x27,
	0x8e, 0xeb, 0x40, 0x77, 0xc7, 0x78, 0xe2, 0xb8, 0xbe, 0x57, 0x0d, 0xba, 0x81, 0xd3, 0xed, 0xd2,
	0x3b, 0x8c, 0x59, 0x7f, 0x19, 0xeb, 0x7f, 0x58, 0x90, 0x1d, 0xaa, 0x3f, 0x46, 0xba, 0x90, 0xd5,
	0x2d, 0x27, 0x15, 0x57, 0x30, 0x77, 0xf3, 0x3f, 0xd9, 0xd5, 0x8d, 0x1d, 0x53, 0xe5, 0x02, 0x8a,
	0x5f, 0x6f, 0x4a, 0x6a, 0x0a, 0xdf, 0x6e, 0xad, 0x5d, 0xdf, 0xda, 0x35, 0x37, 0x6f, 0xe1, 0xf8,
	0xa7, 0x72, 0xd2, 0x52, 0x07, 0x77, 0x3e, 0xa4, 0x6d, 0xef, 0x82, 0x52, 0xa2, 0x41, 0xe3, 0xa9,
	0xae, 0xa7, 0xa3, 0x27, 0x58, 0x6f, 0x8a, 0xfc, 0x6c, 0xaa, 0xa2, 0x4b, 0xc1, 0x58, 0x4e, 0x4f,
	0xc5, 0xf9, 0x67, 0x00, 0x00, 0x00, 0xff, 0xff, 0x6b, 0xac, 0xb1, 0x15, 0x3d, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// HelloClient is the client API for Hello service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type HelloClient interface {
	SayHi(ctx context.Context, in *SayHiRequest, opts ...grpc.CallOption) (*SayHiResponse, error)
	MakeADate(ctx context.Context, in *MakeADateRequest, opts ...grpc.CallOption) (*MakeADateResponse, error)
	UpdateUserInfo(ctx context.Context, in *UpdateUserInfoRequest, opts ...grpc.CallOption) (*UpdateUserInfoResponse, error)
}

type helloClient struct {
	cc grpc.ClientConnInterface
}

func NewHelloClient(cc grpc.ClientConnInterface) HelloClient {
	return &helloClient{cc}
}

func (c *helloClient) SayHi(ctx context.Context, in *SayHiRequest, opts ...grpc.CallOption) (*SayHiResponse, error) {
	out := new(SayHiResponse)
	err := c.cc.Invoke(ctx, "/pb.Hello/SayHi", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *helloClient) MakeADate(ctx context.Context, in *MakeADateRequest, opts ...grpc.CallOption) (*MakeADateResponse, error) {
	out := new(MakeADateResponse)
	err := c.cc.Invoke(ctx, "/pb.Hello/MakeADate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *helloClient) UpdateUserInfo(ctx context.Context, in *UpdateUserInfoRequest, opts ...grpc.CallOption) (*UpdateUserInfoResponse, error) {
	out := new(UpdateUserInfoResponse)
	err := c.cc.Invoke(ctx, "/pb.Hello/UpdateUserInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HelloServer is the server API for Hello service.
type HelloServer interface {
	SayHi(context.Context, *SayHiRequest) (*SayHiResponse, error)
	MakeADate(context.Context, *MakeADateRequest) (*MakeADateResponse, error)
	UpdateUserInfo(context.Context, *UpdateUserInfoRequest) (*UpdateUserInfoResponse, error)
}

// UnimplementedHelloServer can be embedded to have forward compatible implementations.
type UnimplementedHelloServer struct {
}

func (*UnimplementedHelloServer) SayHi(ctx context.Context, req *SayHiRequest) (*SayHiResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayHi not implemented")
}
func (*UnimplementedHelloServer) MakeADate(ctx context.Context, req *MakeADateRequest) (*MakeADateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MakeADate not implemented")
}
func (*UnimplementedHelloServer) UpdateUserInfo(ctx context.Context, req *UpdateUserInfoRequest) (*UpdateUserInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateUserInfo not implemented")
}

func RegisterHelloServer(s *grpc.Server, srv HelloServer) {
	s.RegisterService(&_Hello_serviceDesc, srv)
}

func _Hello_SayHi_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SayHiRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HelloServer).SayHi(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Hello/SayHi",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HelloServer).SayHi(ctx, req.(*SayHiRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Hello_MakeADate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MakeADateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HelloServer).MakeADate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Hello/MakeADate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HelloServer).MakeADate(ctx, req.(*MakeADateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Hello_UpdateUserInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateUserInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HelloServer).UpdateUserInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Hello/UpdateUserInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HelloServer).UpdateUserInfo(ctx, req.(*UpdateUserInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Hello_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Hello",
	HandlerType: (*HelloServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHi",
			Handler:    _Hello_SayHi_Handler,
		},
		{
			MethodName: "MakeADate",
			Handler:    _Hello_MakeADate_Handler,
		},
		{
			MethodName: "UpdateUserInfo",
			Handler:    _Hello_UpdateUserInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "hello.proto",
}
