// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	common_pb "go_project_template/pb/gen-go/common_pb"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetUserNameReq struct {
	BaseReq              *common_pb.BaseReq `protobuf:"bytes,1,opt,name=base_req,json=baseReq,proto3" json:"base_req,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *GetUserNameReq) Reset()         { *m = GetUserNameReq{} }
func (m *GetUserNameReq) String() string { return proto.CompactTextString(m) }
func (*GetUserNameReq) ProtoMessage()    {}
func (*GetUserNameReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{0}
}

func (m *GetUserNameReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserNameReq.Unmarshal(m, b)
}
func (m *GetUserNameReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserNameReq.Marshal(b, m, deterministic)
}
func (m *GetUserNameReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserNameReq.Merge(m, src)
}
func (m *GetUserNameReq) XXX_Size() int {
	return xxx_messageInfo_GetUserNameReq.Size(m)
}
func (m *GetUserNameReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserNameReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserNameReq proto.InternalMessageInfo

func (m *GetUserNameReq) GetBaseReq() *common_pb.BaseReq {
	if m != nil {
		return m.BaseReq
	}
	return nil
}

type GetUserNameRsp struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserNameRsp) Reset()         { *m = GetUserNameRsp{} }
func (m *GetUserNameRsp) String() string { return proto.CompactTextString(m) }
func (*GetUserNameRsp) ProtoMessage()    {}
func (*GetUserNameRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{1}
}

func (m *GetUserNameRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserNameRsp.Unmarshal(m, b)
}
func (m *GetUserNameRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserNameRsp.Marshal(b, m, deterministic)
}
func (m *GetUserNameRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserNameRsp.Merge(m, src)
}
func (m *GetUserNameRsp) XXX_Size() int {
	return xxx_messageInfo_GetUserNameRsp.Size(m)
}
func (m *GetUserNameRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserNameRsp.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserNameRsp proto.InternalMessageInfo

func (m *GetUserNameRsp) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type UpdateUserNameReq struct {
	BaseReq              *common_pb.BaseReq `protobuf:"bytes,1,opt,name=baseReq,proto3" json:"baseReq,omitempty"`
	NewName              string             `protobuf:"bytes,2,opt,name=new_name,json=newName,proto3" json:"new_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *UpdateUserNameReq) Reset()         { *m = UpdateUserNameReq{} }
func (m *UpdateUserNameReq) String() string { return proto.CompactTextString(m) }
func (*UpdateUserNameReq) ProtoMessage()    {}
func (*UpdateUserNameReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{2}
}

func (m *UpdateUserNameReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateUserNameReq.Unmarshal(m, b)
}
func (m *UpdateUserNameReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateUserNameReq.Marshal(b, m, deterministic)
}
func (m *UpdateUserNameReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateUserNameReq.Merge(m, src)
}
func (m *UpdateUserNameReq) XXX_Size() int {
	return xxx_messageInfo_UpdateUserNameReq.Size(m)
}
func (m *UpdateUserNameReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateUserNameReq.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateUserNameReq proto.InternalMessageInfo

func (m *UpdateUserNameReq) GetBaseReq() *common_pb.BaseReq {
	if m != nil {
		return m.BaseReq
	}
	return nil
}

func (m *UpdateUserNameReq) GetNewName() string {
	if m != nil {
		return m.NewName
	}
	return ""
}

type UpdateUserNameRsp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateUserNameRsp) Reset()         { *m = UpdateUserNameRsp{} }
func (m *UpdateUserNameRsp) String() string { return proto.CompactTextString(m) }
func (*UpdateUserNameRsp) ProtoMessage()    {}
func (*UpdateUserNameRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{3}
}

func (m *UpdateUserNameRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateUserNameRsp.Unmarshal(m, b)
}
func (m *UpdateUserNameRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateUserNameRsp.Marshal(b, m, deterministic)
}
func (m *UpdateUserNameRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateUserNameRsp.Merge(m, src)
}
func (m *UpdateUserNameRsp) XXX_Size() int {
	return xxx_messageInfo_UpdateUserNameRsp.Size(m)
}
func (m *UpdateUserNameRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateUserNameRsp.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateUserNameRsp proto.InternalMessageInfo

func init() {
	proto.RegisterType((*GetUserNameReq)(nil), "pb.GetUserNameReq")
	proto.RegisterType((*GetUserNameRsp)(nil), "pb.GetUserNameRsp")
	proto.RegisterType((*UpdateUserNameReq)(nil), "pb.UpdateUserNameReq")
	proto.RegisterType((*UpdateUserNameRsp)(nil), "pb.UpdateUserNameRsp")
}

func init() {
	proto.RegisterFile("user.proto", fileDescriptor_116e343673f7ffaf)
}

var fileDescriptor_116e343673f7ffaf = []byte{
	// 258 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x91, 0x41, 0x4b, 0xfc, 0x30,
	0x10, 0xc5, 0xff, 0x5d, 0xfe, 0xd8, 0x75, 0x0a, 0x0b, 0x8e, 0x28, 0xda, 0x93, 0x54, 0x57, 0xbc,
	0xd8, 0xc2, 0x7a, 0x50, 0xf0, 0x22, 0x7b, 0xf1, 0xe6, 0xa1, 0xd2, 0x8b, 0x97, 0x92, 0xd4, 0xa1,
	0x20, 0x26, 0x99, 0x4d, 0xa2, 0xfb, 0x05, 0xfc, 0xe0, 0x92, 0x14, 0x61, 0x4b, 0xc5, 0xdb, 0xcb,
	0x4c, 0xde, 0xef, 0xe5, 0x11, 0x80, 0x0f, 0x47, 0xb6, 0x64, 0x6b, 0xbc, 0xc1, 0x19, 0xcb, 0xfc,
	0xb8, 0x33, 0x4a, 0x19, 0xdd, 0xb2, 0xac, 0x06, 0x35, 0xec, 0x8a, 0x3b, 0x58, 0x3c, 0x92, 0x6f,
	0x1c, 0xd9, 0x27, 0xa1, 0xa8, 0xa6, 0x0d, 0x5e, 0xc2, 0x5c, 0x0a, 0x47, 0xad, 0xa5, 0xcd, 0x49,
	0x72, 0x96, 0x5c, 0x65, 0xab, 0xac, 0x64, 0x59, 0xae, 0x85, 0x0b, 0xeb, 0x3a, 0x95, 0x83, 0x28,
	0x2e, 0xc6, 0x4e, 0xc7, 0x88, 0xf0, 0x5f, 0x0b, 0x45, 0xd1, 0xb5, 0x5f, 0x47, 0x5d, 0x34, 0x70,
	0xd0, 0xf0, 0xab, 0xf0, 0xb4, 0x1b, 0xb1, 0x84, 0x1f, 0xca, 0x5f, 0x09, 0x78, 0x0a, 0x73, 0x4d,
	0xdb, 0x36, 0x32, 0x67, 0x91, 0x99, 0x6a, 0xda, 0x06, 0x48, 0x71, 0x38, 0xc1, 0x3a, 0x5e, 0x7d,
	0x25, 0x90, 0x86, 0xf3, 0xf3, 0x67, 0x87, 0xb7, 0x90, 0xed, 0xbc, 0x0e, 0x31, 0x04, 0x8c, 0x8b,
	0xe6, 0x93, 0x99, 0xe3, 0xe2, 0x1f, 0x3e, 0xc0, 0x62, 0x4c, 0xc6, 0xa3, 0x70, 0x6f, 0x52, 0x22,
	0xff, 0x6d, 0x1c, 0x08, 0xeb, 0xe5, 0xcb, 0x79, 0x6f, 0x5a, 0xb6, 0xe6, 0x8d, 0x3a, 0xdf, 0x7a,
	0x52, 0xfc, 0x2e, 0x3c, 0x55, 0x2c, 0xab, 0x9e, 0xf4, 0x75, 0x6f, 0x2a, 0x96, 0xf7, 0x2c, 0xe5,
	0x5e, 0xfc, 0x80, 0x9b, 0xef, 0x00, 0x00, 0x00, 0xff, 0xff, 0x79, 0x3f, 0x15, 0x2a, 0xaa, 0x01,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// UserSvcClient is the client API for UserSvc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserSvcClient interface {
	GetUserName(ctx context.Context, in *GetUserNameReq, opts ...grpc.CallOption) (*GetUserNameRsp, error)
	UpdateUserName(ctx context.Context, in *UpdateUserNameReq, opts ...grpc.CallOption) (*UpdateUserNameRsp, error)
}

type userSvcClient struct {
	cc grpc.ClientConnInterface
}

func NewUserSvcClient(cc grpc.ClientConnInterface) UserSvcClient {
	return &userSvcClient{cc}
}

func (c *userSvcClient) GetUserName(ctx context.Context, in *GetUserNameReq, opts ...grpc.CallOption) (*GetUserNameRsp, error) {
	out := new(GetUserNameRsp)
	err := c.cc.Invoke(ctx, "/pb.UserSvc/GetUserName", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userSvcClient) UpdateUserName(ctx context.Context, in *UpdateUserNameReq, opts ...grpc.CallOption) (*UpdateUserNameRsp, error) {
	out := new(UpdateUserNameRsp)
	err := c.cc.Invoke(ctx, "/pb.UserSvc/UpdateUserName", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserSvcServer is the server API for UserSvc service.
type UserSvcServer interface {
	GetUserName(context.Context, *GetUserNameReq) (*GetUserNameRsp, error)
	UpdateUserName(context.Context, *UpdateUserNameReq) (*UpdateUserNameRsp, error)
}

// UnimplementedUserSvcServer can be embedded to have forward compatible implementations.
type UnimplementedUserSvcServer struct {
}

func (*UnimplementedUserSvcServer) GetUserName(ctx context.Context, req *GetUserNameReq) (*GetUserNameRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserName not implemented")
}
func (*UnimplementedUserSvcServer) UpdateUserName(ctx context.Context, req *UpdateUserNameReq) (*UpdateUserNameRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateUserName not implemented")
}

func RegisterUserSvcServer(s *grpc.Server, srv UserSvcServer) {
	s.RegisterService(&_UserSvc_serviceDesc, srv)
}

func _UserSvc_GetUserName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserNameReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserSvcServer).GetUserName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.UserSvc/GetUserName",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserSvcServer).GetUserName(ctx, req.(*GetUserNameReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserSvc_UpdateUserName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateUserNameReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserSvcServer).UpdateUserName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.UserSvc/UpdateUserName",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserSvcServer).UpdateUserName(ctx, req.(*UpdateUserNameReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserSvc_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.UserSvc",
	HandlerType: (*UserSvcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUserName",
			Handler:    _UserSvc_GetUserName_Handler,
		},
		{
			MethodName: "UpdateUserName",
			Handler:    _UserSvc_UpdateUserName_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user.proto",
}
